import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { supabase, ProductVariant } from '@/lib/supabase';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

const variantSchema = z.object({
  variant_type: z.enum(['weight', 'pcs', 'price', 'flavor', 'size']),
  variant_value: z.string().min(1, 'Variant value is required'),
  price: z.coerce.number().min(0, 'Price must be 0 or greater'),
  quantity: z.coerce.number().min(0, 'Quantity must be 0 or greater'),
});

type VariantFormData = z.infer<typeof variantSchema>;

interface VariantFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  itemId: string | null;
  itemName?: string;
  variant?: ProductVariant | null;
  onSuccess: () => void;
}

export default function VariantForm({
  open,
  onOpenChange,
  itemId,
  itemName,
  variant,
  onSuccess,
}: VariantFormProps) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const { profile } = useAuth();

  const form = useForm<VariantFormData>({
    resolver: zodResolver(variantSchema),
    defaultValues: {
      variant_type: 'weight',
      variant_value: '',
      price: 0,
      quantity: 0,
    },
  });

  useEffect(() => {
    if (open) {
      if (variant) {
        // Editing existing variant - populate with current values
        form.reset({
          variant_type: variant.variant_type,
          variant_value: variant.variant_value,
          price: variant.price,
          quantity: variant.quantity,
        });
      } else {
        // Adding new variant - reset to default values
        form.reset({
          variant_type: 'weight',
          variant_value: '',
          price: 0,
          quantity: 0,
        });
      }
    }
  }, [open, variant, form]);

  const onSubmit = async (data: VariantFormData) => {
    if (!itemId) {
      toast({
        variant: 'destructive',
        title: 'Missing item',
        description: 'Please select an item before managing variants.',
      });
      return;
    }

    try {
      setLoading(true);

      if (variant) {
        const { error } = await supabase
          .from('product_variants')
          .update({
            variant_type: data.variant_type,
            variant_value: data.variant_value,
            price: data.price,
            quantity: data.quantity,
            updated_by: profile?.id ?? null,
          })
          .eq('id', variant.id);

        if (error) throw error;

        toast({
          title: 'Variant updated',
          description: 'The variant has been updated successfully.',
        });
      } else {
        // SKU will be auto-generated by the database
        const { error } = await supabase.from('product_variants').insert([
          {
            product_id: itemId,
            variant_type: data.variant_type,
            variant_value: data.variant_value,
            price: data.price,
            quantity: data.quantity,
            updated_by: profile?.id ?? null,
          },
        ]);

        if (error) throw error;

        toast({
          title: 'Variant created',
          description: 'A new variant has been added.',
        });
      }

      onSuccess();
      onOpenChange(false);
    } catch (error: any) {
      toast({
        variant: 'destructive',
        title: 'Error',
        description: error.message || 'Failed to save variant.',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[480px]">
        <DialogHeader>
          <DialogTitle>{variant ? 'Edit Variant' : 'Add Variant'}</DialogTitle>
          <DialogDescription>
            {variant
              ? `Update the variant details for ${itemName ?? 'this item'}.`
              : `Add a new variant option for ${itemName ?? 'this item'}.`}
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="variant_type"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Variant Type</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger className="h-12 rounded-[var(--radius)] border-2 border-border bg-background/50 px-4 py-3 text-base font-medium hover:border-primary/50 focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/20">
                          <SelectValue placeholder="Choose type" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="weight">Weight</SelectItem>
                        <SelectItem value="pcs">Pieces</SelectItem>
                        <SelectItem value="price">Price</SelectItem>
                        <SelectItem value="flavor">Flavor</SelectItem>
                        <SelectItem value="size">Size</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="variant_value"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Variant Value</FormLabel>
                    <FormControl>
                      <Input placeholder="e.g., 250g, 12 pcs" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {variant && (
              <div className="rounded-md bg-muted p-3">
                <p className="text-sm font-medium text-muted-foreground">SKU: <span className="font-mono text-foreground">{variant.sku}</span></p>
                <p className="text-xs text-muted-foreground mt-1">SKU is auto-generated and cannot be changed</p>
              </div>
            )}

            <div className="grid gap-4 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="price"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Price (INR)</FormLabel>
                    <FormControl>
                      <Input type="number" min="0" step="1" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="quantity"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Quantity</FormLabel>
                    <FormControl>
                      <Input type="number" min="0" step="1" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex justify-end gap-3 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
                disabled={loading}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={loading}>
                {loading ? 'Saving...' : variant ? 'Update Variant' : 'Create Variant'}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
